import type { Metadata } from "next";
import { MessageCircle, MapPin, Phone } from "lucide-react";
import { ContactForm } from "@/components/ContactForm";
import { PageHero } from "@/components/PageHero";
import { siteConfig,whatsappUrl } from "@/lib/site";
import { getI18n } from "@/lib/i18n/server";
import { localizedMetadata } from "@/lib/i18n/metadata";

export const generateMetadata=():Promise<Metadata>=>localizedMetadata({title:"Contact",description:"Talk to KrishanTours about a private, tailor-made journey around Sri Lanka.",path:"/contact"});
export default async function ContactPage(){const {t}=await getI18n();return <><PageHero eyebrow={t("Start a conversation")} title={t("Tell us the trip in your head.")} intro={t("Rough dates, half-formed ideas and a list of things you dislike are all welcome.")} image="/images/mirissa.webp"/><section className="bg-[#e8e1d4] py-24 md:py-36"><div className="shell grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:gap-20"><div><p className="eyebrow text-cinnamon">{t("Talk directly")}</p><h2 className="display mt-5 text-6xl leading-[.86]">{t("We’re on")}<br/><em>{t("the island.")}</em></h2><p className="mt-6 max-w-sm text-sm leading-7 text-black/60">{t("We usually reply within one business day. For a quick question, WhatsApp is often easiest.")}</p><div className="mt-9 border-t border-black/15"><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="flex items-center gap-4 border-b border-black/15 py-5"><MessageCircle className="text-cinnamon" size={19}/><span className="text-sm">WhatsApp · {siteConfig.phoneDisplay}</span></a><a href={`tel:${siteConfig.phone}`} className="flex items-center gap-4 border-b border-black/15 py-5"><Phone className="text-cinnamon" size={19}/><span className="text-sm">{t("Call")} · {siteConfig.phoneDisplay}</span></a><div className="flex items-start gap-4 border-b border-black/15 py-5"><MapPin className="mt-0.5 shrink-0 text-cinnamon" size={19}/><address className="text-sm not-italic leading-6">{siteConfig.address.street}<br/>{siteConfig.address.locality}, {siteConfig.address.city}<br/>{t(siteConfig.address.country)} · UTC +5:30</address></div></div></div><ContactForm/></div></section></>}
