import type { Metadata } from "next";
import Image from "next/image";
import Link from "@/components/LocalizedLink";
import { ArrowUpRight } from "lucide-react";
import { PageHero } from "@/components/PageHero";
import { SectionHeading } from "@/components/SectionHeading";
import { stories } from "@/data/stories";
import { getI18n } from "@/lib/i18n/server";
import { localizedMetadata } from "@/lib/i18n/metadata";

export const generateMetadata=():Promise<Metadata>=>localizedMetadata({title:"Island Stories — Sri Lanka Travel Journal",description:"Field notes on Sri Lanka's trains, wildlife, food, coast and ancient places from KrishanTours.",path:"/stories"});
export default async function StoriesPage(){const {t}=await getI18n();const lead=stories[0];return <><PageHero eyebrow={t("Island stories")} title={t("Notes from the road.")} intro={t("Specific places, useful details and the small moments that make a route feel alive.")} image="/images/food.webp"/><section className="py-24 md:py-36"><div className="shell"><SectionHeading eyebrow={t("Field notes & useful detours")} title={<>{t("Read before")}<br/><em>{t("you arrive.")}</em></>}/><Link href={`/stories/${lead.slug}`} className="group mt-14 grid items-center gap-8 bg-jungle text-white lg:grid-cols-[1.2fr_.8fr]"><div className="media-cover aspect-[16/11]"><Image src={lead.image} alt={t(lead.title)} fill sizes="(max-width:1024px) 100vw,60vw" className="object-cover"/></div><div className="p-7 lg:p-10"><p className="eyebrow text-gold">{t("Featured")} · {t(lead.readTime)}</p><h2 className="display mt-5 text-6xl leading-[.84] group-hover:italic">{t(lead.title)}</h2><p className="mt-6 text-sm leading-7 text-white/60">{t(lead.excerpt)}</p><span className="link-arrow mt-8">{t("Read story")} <ArrowUpRight size={15}/></span></div></Link><div className="mt-20 grid gap-x-5 gap-y-16 md:grid-cols-2 lg:grid-cols-3">{stories.slice(1).map((story,index)=><Link href={`/stories/${story.slug}`} key={story.slug} className={`group ${index%3===1?"lg:mt-16":""}`}><div className="media-cover aspect-[4/5]"><Image src={story.image} alt={t(story.title)} fill sizes="(max-width:768px) 180vw,62vw" className="object-cover"/></div><p className="eyebrow mt-5 text-cinnamon">{t(story.category)} · {t(story.readTime)}</p><h2 className="display mt-2 text-4xl leading-none group-hover:italic">{t(story.title)}</h2><p className="mt-3 text-sm leading-6 text-black/55">{t(story.excerpt)}</p></Link>)}</div></div></section></>}
